Add Q&A in FAQ
precice/precice.github.io_old pull request #38
Opened 2019-02-04 14:58 UTC by MakisH

Based on our latest user interaction.

2019-02-05 13:55 UTC, fsimonis commented on 03-faq.md
> +Or: " Is it correct that preCICE cannot support couplings when the interface mesh is changing its connectivity during the simulation?"
```suggestion
Or: "Is it correct that preCICE cannot support couplings when the interface mesh is changing its connectivity during the simulation?"
```

2019-02-05 14:23 UTC, fsimonis commented on 03-faq.md
> +The mapping setup only happens once, in the initialization. So, currently, in order to modify the mapping setup, one needs to restart the simulation, which would be inefficient. However, a dissertati
```suggestion
Currently, the mapping setup only occurs once during the initialization of preCICE. Thus, in order to modify the mapping one must restart the simulation. It depends on a case-by-case basis whether this costly method is acceptable or not.
A dissertation in progress studies this issue and preCICE will have such a feature in the future.
```

2019-02-07 10:02 UTC, fsimonis approved these changes

2019-02-27 09:13 UTC, uekerman requested changes
We have to be careful to have no "wrong" information here. Feel free to alter my suggestions.

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Partitioned coupling can indeed lead to errors such as the Added-Mass Effect. However, preCICE provides implicit coupling algorithms to treat the error introduced.
```suggestion
In general yes, but it depends on the application whether this additional error is problematic. For some applications, e.g. FSI with a compressible fluid, the error can be controlled by the timestep size. For other applications, e.g. FSI with an incompressible fluid and strong coupling, the error can lead to instabilities (the so-called Added-Mass Effects), which in turn can be controlled by the implicit coupling algorithms preCICE offers.
```

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Yes, at least as long as communication over TCP/IP is possible. The participants find each other using a network address, which is written in a file and read once in the beginning of the simulation.
```suggestion
Yes, at least as long as communication over TCP/IP is possible. The solvers find each other using a network address, which is written in a file and read once in the beginning of the simulation. For this reason, all solvers need to be able to at least access a common file system.
```

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Yes! Several people are doing this already and we also kind of do this in our [OpenFOAM-CalculiX FSI tutorial](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX), wh
```suggestion
Yes! Several people are doing this already.
```

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Partitioned coupling can indeed lead to errors such as the Added-Mass Effect. However, preCICE provides implicit coupling algorithms to treat the error introduced.
Not all errors coming from the partitioning can be cured by implicit coupling.

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Yes, at least as long as communication over TCP/IP is possible. The participants find each other using a network address, which is written in a file and read once in the beginning of the simulation.
No need to start the participants from the same directory

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Yes! Several people are doing this already and we also kind of do this in our [OpenFOAM-CalculiX FSI tutorial](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX), wh
Our example, I would not consider a one-way coupling. Might only confuse people.

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +Even though there may be simpler ways to do one-way coupling, it may still be beneficial to use preCICE here: flexible data mapping methods and parallel communication (your coupling data might be too
```suggestion
Even though there may be other ways to do one-way coupling, it may still be beneficial to use preCICE here: flexible data mapping methods, parallel communication (your coupling data might be too large to write to disk), and already adapted solvers.
```

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +A dissertation in progress studies this issue and preCICE will have such a feature in the future.
```suggestion
A dissertation in progress studies dynamically changing coupling meshes, such that preCICE will be able to handle adaptive meshes in the future.
```

2019-02-27 09:13 UTC, uekerman commented on 03-faq.md
> +A dissertation in progress studies this issue and preCICE will have such a feature in the future.
It's a bit unclear to what you refer with "this issue" and "such a feature".

2019-02-27 12:39 UTC, uekerman approved these changes

2019-02-27 17:13 UTC, merged