Style Coupled Codes
precice/precice.github.io_old pull request #41
Opened 2019-02-08 12:19 UTC by fsimonis

This PR:
* Turns the coupled codes into a collection
* Auto-generates the items for the coupled codes
* Restyles the page

# Screenshot
![image](https://user-images.githubusercontent.com/13552216/52477911-e6999800-2ba3-11e9-86aa-00a19d26a40b.png)

2019-02-08 18:04 UTC, MakisH requested changes

2019-02-08 18:04 UTC, MakisH commented on 04-codes.md
> +      <dt>Adapter's repository:</dt>
Since we are converting this to cards, I think it would be nice to use the status in the top-right corner of the card title row, if this is easily doable.

2019-02-08 18:04 UTC, MakisH commented on 04-codes.md
> +{% assign official = site.codes | where: "category", "official" %}
In the current, non-automatic implementation, the solvers are sorted manually by importance/popularity/status (of course with a lot of randomness).

One solution (dirty workaround) would be to name the entry files starting with numbers.

Another solution would be to use the "status" for sorting, so that we don't show out-of-date adapters on the top.

And of course, another solution would be to keep all of our adapters up-to-date, but I assume this is not possible in the near future.

2019-02-08 18:09 UTC, MakisH commented on 04-codes.md
> +       {% when 'experimental' %}
I would distinguish between "experimental" and "out-of-date". In this sense, I would rather set "experimental" as "warning".

2019-02-08 20:21 UTC, fsimonis commented on 04-codes.md
> +       {% when 'experimental' %}
Done

2019-02-08 20:22 UTC, fsimonis commented on 04-codes.md
> +      <dt>Adapter's repository:</dt>
I tried a few different ways and I decided to use some icons. This has a clean look and prevents problems on smaller sizes. I also added the status as clear text in the body.

2019-02-08 20:24 UTC, fsimonis commented
New version implementing the feedback regarding the status location and format:
![image](https://user-images.githubusercontent.com/13552216/52504111-ba076f80-2be7-11e9-9168-ccf983c371b3.png)

The icons display the status as text on hover.

2019-02-09 09:42 UTC, MakisH commented
This looks much much better!

Two language issues:
* `is needs-small-updates` (Code_Aster) --> Maybe rename `needs-small-updates` to `potentially out-of-date` and you are done.
* the phrasing suggests that the *repository* is up-to-date/experimental etc, while we mean that the code/adapter has this property. By the way, I think that in case of Fluent (@BenjaminRueth), the adapter is `experimental`, but the GitHub repository is `out-of-date.

2019-02-09 10:57 UTC, fsimonis commented
@MakisH Thanks!
I try not to mess around with the already used keywords too much.

What about the following:
![image](https://user-images.githubusercontent.com/13552216/52519837-dba53d00-2c61-11e9-9cba-6f870ed7edac.png)

2019-02-09 11:39 UTC, MakisH commented
Well, I set these keywords a while ago, so no worries about any side-effects.

In the last image I don't like that we mix natural, human-friendly language and a technical, implementation-specific term. It sounds a bit like `The flight [...] A [...] 3 [...] 8 [...] 0 [...] 2 [...] to [...] Munich Franz-Josef Straus [...] is [...] ready to board`.

The content we can change in a separate PR, but since these terms get semantics now, I would suggest that we change this now (or assign a human-friendly string to each status).

Small language fix: I would add a "the" in front of the adapter, or remove the "is".

2019-02-09 18:27 UTC, shkodm requested changes

2019-02-09 18:27 UTC, shkodm commented on 04-codes.md
> +    fa-info-circle
I believe `fa-exclamation-circle` should be better here, `fa-info-circle` suggest that it provides some information about the adapter, which is not really the case.

2019-02-09 18:27 UTC, shkodm commented on 04-codes.md
> +    fa-minus-circle
`fa-minus-circle` looks too absolute and negative.  I would use `fa-archive`, that is somehow more visually indicates that it is out of date

2019-02-09 18:27 UTC, shkodm commented on _sass/precice/_codeslist.scss
> +                margin-left: auto;
I think there should be no margin between name of the adapter and the status, like this (maybe with different size)
![image](https://user-images.githubusercontent.com/13331189/52524699-47a69600-2ca0-11e9-982f-e4ecee7ee15b.png)

Otherwise if the status is in the right corner of the box, you will not even immedeately understand ( I did not at first) that it is status and not just visual decoration

2019-02-10 09:13 UTC, MakisH commented on 04-codes.md
> +    fa-info-circle
Actually, that's a good point.

2019-02-10 09:33 UTC, MakisH commented on 04-codes.md
> +    fa-info-circle
Maybe we could have a "?" here (especially if we change to "potentially out-of-date") and a "!" in the out-of-date ones.

2019-02-10 09:38 UTC, MakisH commented on 04-codes.md
> +    fa-minus-circle
I agree with the `fa-minus-circle` being too absolute and negative, but I don't agree with the `fa-archive`, since we may revive these at any time.

I would prefer something that points to something old and dusty. How about:
* [`fa-dragon`](https://fontawesome.com/icons/dragon?style=solid) (I could find no dinosaur)
* [`fa-treasure-chest`](https://fontawesome.com/icons/treasure-chest?style=regular) (only in Pro, but I have an unused license)
* [`fa-scroll-old`](https://fontawesome.com/icons/scroll-old?style=regular) (again, only Pro)
* [`fa-heart-broken`](https://fontawesome.com/icons/heart-broken?style=solid) (broken code, broken heart!)
* [`fa-skull-crossbones`](https://fontawesome.com/icons/skull-crossbones?style=solid) (dead code, although maybe too negative again)
* [`fa-dungeon`](https://fontawesome.com/icons/dungeon?style=solid) ("you have to go to our dungeons for this")

I am not satisfied with any of these, but maybe they trigger some better idea. I think there is room for humor in our "out-of-date" adapters, showing that they are dangerous, but at the same time showing that it's not so bad and could be revived.

2019-02-10 09:41 UTC, MakisH commented on _sass/precice/_codeslist.scss
> +                margin-left: auto;
I think that it looks a bit weird like this. I actually like them on the right side, but we could solve this by simply putting them on the left side (which would again look a bit strange).

I actually did not have any problems understanding the meaning, but I am not the average visitor of the website.

2019-02-10 09:47 UTC, shkodm commented on 04-codes.md
> +    fa-minus-circle
Nice suggestions.  I think `fa-scroll-old` actually looks better than `archive`

2019-02-10 10:04 UTC, shkodm commented on 04-codes.md
> +    fa-info-circle
I just tested locally and I'm not sure, that `question-circle` would convey meaning better. It is somehow more similar to `info-circle`, suggesting, that by hovering over you get information like "what is it?" ( e.g. what is this adapter )

2019-02-10 10:06 UTC, shkodm commented on _sass/precice/_codeslist.scss
> +                margin-left: auto;
I think somehow if you put too much empty space between name of the adapter and status, one could think that icon indicating status are just for decoration. They don't need to be next to each but maybe just with a smaller margin.

2019-02-18 21:42 UTC, fsimonis commented
After reflecting on the feedback, I put together the following layout:

We only use 3 icons for:
* Experimental
* Up-to-date
* Out-of-date

We then put the icon in front of the title, so that it doesn't look like odd decoration.
This results in nicely aligned icons as well as titles.

![image](https://user-images.githubusercontent.com/13552216/52977307-17ac7080-33cd-11e9-8182-a84db42fcb09.png)

2019-02-18 22:05 UTC, MakisH commented
I like it! Can we still have a custom order, or at least show the up-to-date before the out-of-date?

2019-02-19 10:39 UTC, uekerman commented
I like it too!

On Mon, Feb 18, 2019, 11:05 PM Gerasimos Chourdakis <
notifications@github.com wrote:

> I like it! Can we still have a custom order, or at least show the
> up-to-date before the out-of-date?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/precice/precice.github.io/pull/41#issuecomment-464897912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACxFiEjFuAnNphVKIsxrQlMJVtiGTFG9ks5vOyO-gaJpZM4avWd3>
> .
>

2019-02-25 11:45 UTC, fsimonis commented
@MakisH yes we can have a custom order. What do you recommend?

2019-02-25 11:53 UTC, MakisH commented
> @MakisH yes we can have a custom order. What do you recommend?

I would stick more-or-less to the one we currently have (with small updates):

1. OpenFOAM
2. FEniCS
3. CalculiX
4. SU2
5. Code_Aster
6. Fluent
7. COMSOL

I sort them with a heuristic algorithm that uses as input the activity of our adapter and the popularity of the solver. But this is a discussion for another PR. Let's just set the mechanism now.

2019-02-25 12:37 UTC, fsimonis commented
I added an order for the official adaptors. Any other feedback, or can I merge?

2019-02-25 14:39 UTC, merged