Add a coupled code card for deal.II
precice/precice.github.io_old pull request #52
Opened 2019-06-21 20:46 UTC by DavidSCN

Closes #49.

I have not viewed at the website locally, so please check the result before merging.

2019-06-22 16:32 UTC, shkodm commented
I've just checked locally. Looks good.

2019-06-22 16:39 UTC, shkodm commented on _codes/dealii.md
> +Build status:<a style="text-decoration: none" href="https://travis-ci.org/precice/dealii-adapter" target="_blank"><img src="https://travis-ci.org/precice/dealii-adapter.svg?branch=master" alt="Build
Add one space after build status, before travis status. Otherwise the margin is too small.

2019-06-22 16:39 UTC, shkodm approved these changes

2019-06-22 16:41 UTC, shkodm commented
Also, should some tutorial with `deal.ii` to the `resources` section?

2019-06-22 17:59 UTC, DavidSCN commented on _codes/dealii.md
> +Build status:<a style="text-decoration: none" href="https://travis-ci.org/precice/dealii-adapter" target="_blank"><img src="https://travis-ci.org/precice/dealii-adapter.svg?branch=master" alt="Build
Hope it's better now.

2019-06-22 18:01 UTC, DavidSCN commented
> Also, should we add some tutorial with deal.ii to the `resources` section?

Good question, maybe @MakisH knows. is this related to #45 ?

2019-06-23 21:03 UTC, MakisH requested changes
This builds nicely (it's very easy to try it locally, have a look at the README).

The information looks good. However, please:
- [x] Add the supported deal-II versions (even if you only know one)
- [x] Move the card up (e.g. before or after FEniCS)

Regarding the [Resources](https://www.precice.org/resources/) page: The page is not currently designed to point to different variants of each tutorial (or, let's say, many combinations that we have documented are missing). In terms of physics/geometry we don't need to add anything. If you want to add anything, you could use a different screenshot. In any case, this is a different issue, related to https://github.com/precice/tutorials/issues/28.

2019-06-24 09:10 UTC, DavidSCN commented
Concerning the version: Most of  the used functions are quiet basic. So, I cannot really say, which deal.II version are going to work and which not. Of course, I could mention there the most recent version the adapter has been built on. But this is probably a restriction.

2019-06-24 10:36 UTC, MakisH approved these changes

2019-06-24 10:37 UTC, MakisH commented
> Concerning the version: Most of the used functions are quiet basic. So, I cannot really say, which deal.II version are going to work and which not. Of course, I could mention there the most recent version the adapter has been built on. But this is probably a restriction.

Still, giving one specific "known-to-work" version to the user is invaluable. I fixed the field and added more information. LGTM.

2019-06-24 16:44 UTC, merged