Add Funding
precice/precice.github.io_old pull request #53
Opened 2019-06-26 14:48 UTC by fsimonis

This PR adds the funding information to the end of the welcome page.

# Preview
![image](https://user-images.githubusercontent.com/13552216/60189968-1fc06500-9832-11e9-9c44-22073212fd24.png)

2019-06-26 15:35 UTC, MakisH requested changes
From a content structure perspective, I think it makes more sense that this information goes into the About page. There it would also be nice to have the university logos together with the people.

In respect to the aesthetics, maybe a horizontal positioning would be better, at least if it stays in the Welcome page, which is already very bloated at the moment. Again, moving it in the About hides a bit of the bloat.

Small detail regarding the BMWi logo: since our website is in English, I would also use the English version of the logo, see https://www.bmwi.de/Navigation/EN/Home/home.html

2019-06-26 18:15 UTC, fsimonis commented
@MakisH I am against putting this information into the about page as it would bloat it up even more.
However, I definitely agree with a horizontal positioning for big screens.

Working on the website again makes me realise that the entire website needs tidying up. Information is all over the place and barely structured. We need to collect user concerns and align the structure towards that.

2019-06-28 06:45 UTC, MakisH commented
> @MakisH I am against putting this information into the about page as it would bloat it up even more.
> However, I definitely agree with a horizontal positioning for big screens.

I guess this needs longer discussion, looking at more aspects. For me and at the moment, it looks reasonable that the funding (that supports the developers) is on the same page with the developers.

2019-06-30 16:25 UTC, uekerman commented
I agree with @MakisH: should go to the about page. But you're right: having a proper discussion on how to arrange things on the web site is sth we should do soonish.

2019-07-01 10:58 UTC, fsimonis commented
I moved the list to the about page and made it responsive

2019-07-01 12:15 UTC, uekerman approved these changes

2019-07-02 07:56 UTC, MakisH requested changes
Looks good! Please check my minor suggestions regarding headings and spacing.

2019-07-02 07:56 UTC, MakisH commented on 08-about.md
> +## This project is funded by:
```suggestion
## Funding

This project is funded by:
```

2019-07-02 07:56 UTC, MakisH commented on 08-about.md
>  This website is maintained by
```suggestion
## Impressum

This website is maintained by
```

2019-07-02 07:56 UTC, MakisH commented on _sass/precice/_funding.scss
> +        margin-top: 1em;
```suggestion
        margin-top: 2em;
```

2019-07-02 07:56 UTC, MakisH commented on _sass/precice/_funding.scss
> +        margin-top: 1em;
On my screen the funding logos appear in two rows and with `1em` they look a bit packed.

2019-07-02 08:08 UTC, fsimonis commented on _sass/precice/_funding.scss
> +        margin-top: 1em;
I agree! `2em` looks better.

2019-07-02 08:13 UTC, fsimonis commented
@MakisH with the separate headers it looks a bit strange/redundant:
<details>
<summary>click to expand</summary>

![image](https://user-images.githubusercontent.com/13552216/60495825-d3ea4180-9cb1-11e9-9abe-5b5f22dcab45.png)

</details>

2019-07-02 08:23 UTC, MakisH commented
Since we have the heading `## Development`, we definitely need the headings `## Funding` and `## Impressum` as well. Feel free to remove the redundant description, though.

Note that `## This project is funded by:` would be inconsistent (from language and ":" perspective).

2019-07-08 23:13 UTC, MakisH approved these changes

2019-07-09 11:49 UTC, merged