Workshop
precice/precice.github.io_old pull request #57
Opened 2019-09-21 16:44 UTC by MakisH

I added a few more information for the workshop:
* Link to the registration form
* Call for contributions
* Note to avoid flying
* Recommended hotel skeleton text

Will not be merged until we have all the missing information.

![Screenshot from 2019-09-21 18-40-49](https://user-images.githubusercontent.com/4943683/65376407-ac4aba00-dc9f-11e9-8487-fbf31a9f28e5.png)

2019-10-01 14:42 UTC, uekerman requested changes

2019-10-01 14:42 UTC, uekerman commented on 09-workshop.md
> +We would be very happy if you could choose a train or other environmentally-friendly ways to come to Munich. Please avoid flying!
```suggestion
We would be very happy if you could choose a train or other environmentally-friendly ways to come to Munich. Please avoid flying if possible.
```

2019-10-01 14:42 UTC, uekerman commented on 09-workshop.md
> +* September 27: Registration opens.
Let's update this before merging.

2019-10-01 16:27 UTC, MakisH commented on 09-workshop.md
> +* September 27: Registration opens.
I removed it for now.

2019-10-07 13:59 UTC, uekerman approved these changes

2019-10-07 13:59 UTC, uekerman commented on 09-workshop.md
> +* 10:20 - 11:00 Coffee Break
```suggestion
* 10:30 - 11:00 Coffee Break
```

2019-10-07 13:59 UTC, uekerman commented on 09-workshop.md
> +* November 15: End or early registration, abstract submission deadline, travel grant application deadline.
```suggestion
* November 15: End of early registration, abstract submission deadline, travel grant application deadline.
```

2019-10-07 14:29 UTC, merged